### ISSUE TITLE
FakePlayer Support

### ISSUE THREAD

**Issue by ghost** [3arthqu4ke/PingBypassClient#8]
Hi there,

I am creating an issue here as I cannot find any other form of contact to speak to you directly and your Discord friend requests are closed. I have seen with 3arthh4ck / Phobos 2.0.0 that the FakePlayer is able to process damage ticks and totem pops. Could you please let me know how you do this, and if possible with code examples? 

Apologies for contacting you via Github, I would have contacted you via a more convenient platform but it seems that's not possible. 

I look forward to hear from you, thanks! :)

**Comment by 3arthqu4ke** [comment]
You can pop an Entity by using:
```java
entity.handleStatusUpdate(35);
```
But you'll have to set health and potion effects manually.

For damaging an Entity check out the code of:
```java
EntityLivingBase.attackEntityFrom(DamageSource source, float amount)
```
It requires some rewriting, since it doesn't work if the entity is in a client world. AutoCrystal calculations should already give you DamageSource and amount for applying explosion damage.
